export type Forretningshaendelse =
  | 'Ejerskifte tilbageført'
  | 'Landsdækkende kørsel'
  | 'Opdatering af ejendomsadministrator'
  | 'Annulleret personnummer'
  | 'Personnummer nedlagt pga. dobbeltregistrering'
  | 'Person død'
  | 'Person udrejst'
  | 'Person forsvundet'
  | 'Opdatering af administrator for person eller virksomhed'
  | 'Opdatering af ejer uden registreret CPR- eller CVR nummer'
  | 'Ophør af en produktionsenhed'
  | 'Ophør af virksomhed'
  | 'Skift af virksomhedsform'
  | 'Administrator af ejerskab'
  | 'Ægtepagt adkomst'
  | 'Aflysning af betinget skøde'
  | 'Aflyst eller annulleret ejerskab'
  | 'Anden adkomst'
  | 'Auktionsskøde'
  | 'Betinget bodeling'
  | 'Betinget skøde'
  | 'Bodeling'
  | 'Ejendomsdom'
  | 'Indberettet ejerskifte'
  | 'Endelig indførsel adkomst'
  | 'Endeligt skøde'
  | 'Hævd'
  | 'Kopieret ejerskab til ny ejendom'
  | 'Meddelelse fast ejendom adkomst'
  | 'Meddelelse om tvangsauktion'
  | 'Navneændring'
  | 'Opdatering af person- eller virksomhedsoplysninger'
  | 'Opretning af ejerandele'
  | 'Oprettet ejerskab af ny ejendom'
  | 'Rettelse af ejerskab'
  | 'Skifteretsattest'
  | 'SkifteretsattestÆgtefælle'
  | 'Påtegning adkomst'
  | 'Ukendt - konverteret fra ESR';

